### ISSUE TITLE
Revise/improve generated probe documentation

### ISSUE THREAD

**Issue by chipbarnaby** [cse-sim/cse#395] opened 2023-05-18 14:45 UTC
Possible improvements --

- Capture multi-line comments from cnrecs.def.  Currently it appears only the first comment is captured (?)
- Retain cnrecs.def text as written.  Currently too much cleverness such as changing case.
- Consider added cnrecs.def additional syntax that allows tagging text as "for documentation"
- Change format of generated documentation to provide wider column for documentation text.  Text is now scrunched over on right side of layout.  Reduce size of "Input" and "Runtime" columns, perhaps by adding a coded "attributes" column ?

**Comment by nealkruis** [comment] 2023-05-23 17:32
Duplicate of #217.

**Closed** 2023-05-23 17:32 UTC
Labels: documentation
