### ISSUE TITLE
Some heading numbers in multi-page HTML aren't correct

### ISSUE THREAD

**Issue by nealkruis** [cse-sim/cse#13] opened 2017-04-26 21:24 UTC
For example: [DOOR](https://cse-sim.github.io/cse/cse-user-manual/door.html#door) is 0.3 (in both it's page and in the table of contents)

**Comment by michael-okeefe** [comment] 2017-12-01 14:00
Closing this as it is a duplicate of issue #20

**Closed by michael-okeefe** 2017-12-01 14:00 UTC
Labels: bug, documentation
