### ISSUE TITLE
Documentation coverage bug for multi-item groups

### ISSUE THREAD

**Issue by chipbarnaby** [cse-sim/cse#65] opened 2019-05-09 20:37 UTC
The documentation coverage detectorizer is not handling item groups, see example.

Example - DHWSYS.md

wsFaucetCount=integer
wsShowerCount=integer
wsBathCount=integer
wsCWashrCount=integer
wsDWashrCount=integer

Specifies the count of fixtures served by this DHWSYS that can accommodate draws of each end use (see DHWUSE). blah blah blah

>>> The coverage report lists all of these items except wsDWashrCount as "in CSE but not documentation"

**Comment by michael-okeefe** [comment] 2020-01-31 19:21
See https://github.com/cse-sim/cse/pull/86.
Duplicate of https://github.com/cse-sim/cse/issues/81

**Comment by michael-okeefe** [comment] 2020-01-31 19:22
Duplicate of https://github.com/cse-sim/cse/issues/81

**Comment by galanCA** [comment] 2022-04-01 15:22
@nealkruis This issue seems to be resolve.

**Comment by nealkruis** [comment] 2022-04-01 15:58
Closing because this is a duplicate.

**Closed by nealkruis** 2022-04-01 15:58 UTC
Labels: documentation
